spring:
  messages:
    basename: message, errors

  datasource:
    url: jdbc:h2:tcp://localhost/~/myshop
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #애플리케이션 실행 시점에 테이블 지우고 다시 생성
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug